name = "Graduent Student Story"
description = "-"

packages = ["markdown", "asyncio"]

[files]
"./main.py" = ""
"./game.py" = ""
"./entity.py" = ""
"./ui.py" = ""
"./test.py" = ""
"story/__init__.py" = "story/__init__.py"
"story/chapter0/__init__.py" = "story/chapter0/__init__.py"
"story/chapter0/scene0.py" = "story/chapter0/scene0.py"
"story/chapter0/scene1.py" = "story/chapter0/scene1.py"
"story/chapter0/scene2.py" = "story/chapter0/scene2.py"
