name = "Graduent Student Story"
description = "-"

packages = ["markdown", "asyncio", "pydantic"]

[files]
"./main.py" = ""
"./game.py" = ""
"./entity.py" = ""
"./ui.py" = ""
"./test.py" = ""
"./scene.py" = ""
"./scene_manager.py" = ""
"./const.py" = ""
"./logic_handlers.py" = ""
"./schemas.py" = ""

# Story
"story/__init__.py" = "story/__init__.py"
# Chapter 0
"story/chapter0/__init__.py" = "story/chapter0/__init__.py"
"story/chapter0/ch0scene0.py" = "story/chapter0/ch0scene0.py"
"story/chapter0/ch0scene1.py" = "story/chapter0/ch0scene1.py"
"story/chapter0/ch0scene2.py" = "story/chapter0/ch0scene2.py"
# Chapter 1
"story/chapter1/__init__.py" = "story/chapter1/__init__.py"
"story/chapter1/ch1common.py" = "story/chapter1/ch1common.py"
"story/chapter1/ch1scene0.py" = "story/chapter1/ch1scene0.py"
"story/chapter1/ch1scene1.py" = "story/chapter1/ch1scene1.py"
"story/chapter1/ch1scene2_0.py" = "story/chapter1/ch1scene2_0.py"
"story/chapter1/ch1scene2_1.py" = "story/chapter1/ch1scene2_1.py"
"story/chapter1/ch1scene2_2.py" = "story/chapter1/ch1scene2_2.py"
"story/chapter1/ch1scene2_3.py" = "story/chapter1/ch1scene2_3.py"
"story/chapter1/ch1scene2_4.py" = "story/chapter1/ch1scene2_4.py"
"story/chapter1/ch1scene2_5.py" = "story/chapter1/ch1scene2_5.py"
"story/chapter1/ch1scene2_6.py" = "story/chapter1/ch1scene2_6.py"
"story/chapter1/ch1scene2_7.py" = "story/chapter1/ch1scene2_7.py"
"story/chapter1/ch1scene3_0.py" = "story/chapter1/ch1scene3_0.py"
"story/chapter1/ch1scene3_1.py" = "story/chapter1/ch1scene3_1.py"
"story/chapter1/ch1scene3_2.py" = "story/chapter1/ch1scene3_2.py"
"story/chapter1/ch1scene3_3.py" = "story/chapter1/ch1scene3_3.py"
"story/chapter1/ch1scene3_4.py" = "story/chapter1/ch1scene3_4.py"
"story/chapter1/ch1scene4_0.py" = "story/chapter1/ch1scene4_0.py"
"story/chapter1/ch1scene4.py" = "story/chapter1/ch1scene4.py"
"story/chapter1/ch1scene5.py" = "story/chapter1/ch1scene5.py"
"story/chapter1/ch1scene6.py" = "story/chapter1/ch1scene6.py"
"story/chapter1/ch1scene7.py" = "story/chapter1/ch1scene7.py"
"story/chapter1/ch1scene8.py" = "story/chapter1/ch1scene8.py"
"story/chapter1/ch1scene9.py" = "story/chapter1/ch1scene9.py"
"story/chapter1/ch1scene10.py" = "story/chapter1/ch1scene10.py"
